### ISSUE TITLE
Updates to acceptedPlots

### ISSUE THREAD

**Issue by rkrauss** [schafnoir/neonPlantSampling#1]
Hello plant gitters-

I have added plot spatial information for 11 sites, some new, some old.  
The new sites are:  OAES, SRER, SERC, GRSM,and DELA.   
The old sites are:  BART, TALL, OSBS, DSNY, JERC, and ORNL.   

I am not aware of changes for the old sites-  we have just updated the delivery format and wanted to provide all sites with the same information moving forward.  If there is a site that you need the information for sooner than later then let us know. 

thanks- 
 the spatial cats

**Comment by schafnoir** [comment]
Perfect - thanks Rachel!

**Comment by lstanish** [comment]
Thanks Rachel! Any chance you can indicate which plots are for bgc|sme in
the new files?

On Wed, Mar 11, 2015 at 3:44 PM, Rachel Krauss <notifications@github.com>
wrote:

> Hello plant gitters-
>
> I have added plot spatial information for 11 sites, some new, some old.
>
> The new sites are: OAES, SRER, SERC, GRSM,and DELA.
>
> The old sites are: BART, TALL, OSBS, DSNY, JERC, and ORNL.
>
> I am not aware of changes for the old sites- we have just updated the
> delivery format and wanted to provide all sites with the same information
> moving forward. If there is a site that you need the information for sooner
> than later then let us know.
>
> thanks-
> the spatial cats
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schafnoir/neonPlantSampling/issues/1>.
>



-- 
Lee Stanish
Microbial Ecologist at NEON, Inc.
INSTAAR Affiliate
Boulder, CO, USA

**Comment by schafnoir** [comment]
I think that Dave is doing that still. Correct me if I’m wrong Spatial Cats!

On 13 Mar 2015, at 14:40, Lee Stanish <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks Rachel! Any chance you can indicate which plots are for bgc|sme in
the new files?

On Wed, Mar 11, 2015 at 3:44 PM, Rachel Krauss <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Hello plant gitters-
>
> I have added plot spatial information for 11 sites, some new, some old.
>
> The new sites are: OAES, SRER, SERC, GRSM,and DELA.
>
> The old sites are: BART, TALL, OSBS, DSNY, JERC, and ORNL.
>
> I am not aware of changes for the old sites- we have just updated the
> delivery format and wanted to provide all sites with the same information
> moving forward. If there is a site that you need the information for sooner
> than later then let us know.
>
> thanks-
> the spatial cats
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schafnoir/neonPlantSampling/issues/1>.
>



--
Lee Stanish
Microbial Ecologist at NEON, Inc.
INSTAAR Affiliate
Boulder, CO, USA

**Comment by lstanish** [comment]
OK, all good here.
Thanks!

On Fri, Mar 13, 2015 at 2:51 PM, Courtney Meier <notifications@github.com>
wrote:

> I think that Dave is doing that still. Correct me if I’m wrong Spatial
> Cats!
>
> On 13 Mar 2015, at 14:40, Lee Stanish <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> Thanks Rachel! Any chance you can indicate which plots are for bgc|sme in
> the new files?
>
> On Wed, Mar 11, 2015 at 3:44 PM, Rachel Krauss <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > Hello plant gitters-
> >
> > I have added plot spatial information for 11 sites, some new, some old.
> >
> > The new sites are: OAES, SRER, SERC, GRSM,and DELA.
> >
> > The old sites are: BART, TALL, OSBS, DSNY, JERC, and ORNL.
> >
> > I am not aware of changes for the old sites- we have just updated the
> > delivery format and wanted to provide all sites with the same
> information
> > moving forward. If there is a site that you need the information for
> sooner
> > than later then let us know.
> >
> > thanks-
> > the spatial cats
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/schafnoir/neonPlantSampling/issues/1>.
> >
>
>
>
> --
> Lee Stanish
> Microbial Ecologist at NEON, Inc.
> INSTAAR Affiliate
> Boulder, CO, USA
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/schafnoir/neonPlantSampling/issues/1#issuecomment-79366393>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schafnoir/neonPlantSampling/issues/1#issuecomment-79379344>
> .
>



-- 
Lee Stanish
Microbial Ecologist at NEON, Inc.
INSTAAR Affiliate
Boulder, CO, USA
