### ISSUE TITLE
HARV_plotSpatialData.csv not standard file format

### ISSUE THREAD

**Issue by schafnoir** [schafnoir/neonPlantSampling#4]
@eazuaje @jalynda @gitbarnitt 
Hey folks,
Was just running the code through the [siteID]_plotSpatialData.csv files to do random subplot selection for Tower plots, and found that the following files have not yet been replaced with the new code-standardized version of the output:
HARV
ONAQ
SCBI
STER
UNDE
WOOD

Either that, or I am daft and accidentally overwrote the new ones that you already made? A distinct possibility... either way, would it be possible to get the new standard versions for these sites pushed to Git (again maybe)?

Many thanks, and sorry if I'm being a buffoon of a Git user!
CM

**Comment by jalynda** [comment]
I don't think it was your lack of Git skills. I'm in the process of updating STER, ONAQ, SCBI. Hopefully by the end of the week.

JM
