### ISSUE TITLE
Blandy accepted plot list

### ISSUE THREAD

**Issue by schafnoir** [schafnoir/neonPlantSampling#7]
@jalynda @eazuaje @rkrauss 
Hey there good people-
I'm sitting here in the JIRA meeting, and Greg Chapman in D02 indicated they will need their Clip Lists soon (next week?) in order to begin litter trap deployment. Do you think that will be possible?

Cheers,
CM

**Comment by jalynda** [comment]
Yes! That can be done later today.

**Comment by schafnoir** [comment]
Perfect - you are Señorita Speedy von PlotPoints!

On 23 Apr 2015, at 12:13, jalynda <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes! That can be done later today.
