### ISSUE TITLE
applicableModule differences across sites

### ISSUE THREAD

**Issue by schafnoir** [schafnoir/neonPlantSampling#9]
@gitbarnitt @jalynda @rkrauss @eazuaje 

Hey there folks,

This evening I was working on the code that reads data from "SITE_plotSpatialData.csv" files you've been uploading here, and then generates random azimuths to support CDW sampling. As I was going through each site, I noticed something I thought was odd. But hopefully I'm just forgetting something that one of you can clarify for me! 

Basically, everything works fine when I create the CDW azimuths for tower plots. However, for distributed plots, I am reading in the list of plots for each site, and then I use dplyr and a grepl approach to snag only those plotIDs that have 'cdw' in the 'applicableModules' field and have subtype = 'distributed'. I was expecting a maximum of 20 plots that meet these conditions per site, but very often it is 30 plots (or 28 at OSBS). I've summarized the number of distributed plots containing 'cdw' in the applicableModules string in an Excel file I put in the root directory of this repository (cdw_applicableModSummary.xlsx).

How come some sites have 20 plots for 'cdw' (as well as the other biomass-y modules, like hbp, vst, and dhp), and others have 30? Since I only want the techs to consider implementing the cdw protocol (and hbp, vst, and dhp protocols) in up to 20 distributed plots, if I cut the list down to the first 20 plotIDs, will these 20 still be random given the way the lists were put together? I'm reticent to give them a list that contains 30 when I only want them to do 20 plots (max), as I'm sure the techs will get "creative."

Thanks for your help!
CM

**Comment by gitbarnitt** [comment]
Hmmm.  It should only be 20.  It might be that we pluck the plots we hand you could be upstream if the final determinations.  Can you give me an example of a site to check?

db

**Comment by schafnoir** [comment]
Hey Dave,

I tested each of the 'SITE_plotSpatialData.csv' files, and summarized the results in that .xlsx file I posted to Git. If you pull from the 'neonPlantSampling' repository, you should find the file right in the root directory of the repository. It's called 'cdw_applicableModSummary.xlsx'. If you can't get the file for some reason though, BART is the first one I noticed.

But don't work too late!

CM

On 5 May 2015, at 21:29 , gitbarnitt <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmmm. It should only be 20. It might be that we pluck the plots we hand you could be upstream if the final determinations. Can you give me an example of a site to check?

db

**Comment by gitbarnitt** [comment]
Clearly not reading carefully from the phone.  I might have a look tonight, might not.  It should be an easy fix.  We also provide them a todo list - applicableModule by plot - and those, I'm pretty dam sure, are only 20 Courtney modules per site at distributed plots.  That should also guide/constrain FOPS activities, but we'll want it all same standard regardless.  

night!

**Comment by rkrauss** [comment]
Morning!

Took a quick look-  all the sites that 20+ distributed plots with cdw sampling are "older" sites and it looks like there was a change to the code that has since updated the applicable modules field to indicate only 20 distributed plots.   

I checked a few FOPs folders and their sheets all indicate only 20 distributed plots for this sampling and the latest outputs from the code from these sites also only have 20 distributed plots meaning the latest data to CI looks good and the information that FOPs received was always good!  The final step (and our apologies for not updating the git folder) is to push the latest outputs to the acceptedPlots folder.  
Locations/PlotIds/most of the good stuff is exactly the same just tweaks to other fields, including applicable modules.

The only sites that will have less than 20 distributed plots for these activities are STEI (12 plots) and OSBS (19) plots and both these numbers are reflected in the csv FOPs receive. 

I will update the sites before today's FSU meeting. 

Wahoo!  
RK

**Comment by gitbarnitt** [comment]
Fantastic, thanks for looking into this!!!

**Comment by rkrauss** [comment]
Hello-

Just updated the plot spatial data csvs for 12 sites.   

The locations, plot IDs, plot types, and subtypes have not been altered from the previous versions.  The main update was to reflect the updates in applicable modules for plant sampling in distributed plots to match the information that CI and FOPs receive. 

The sites that have been updated are:
BART
DELA
DSNY
GRSM
JERC
OAES
ORNL
OSBS
SCBI
SERC
SRER
TALL

Let us know if you have any questions! 

RK

**Comment by schafnoir** [comment]
Hey Rachel-

Did you push the updates to Git? It seems to me that all the files are still the same in the acceptedPlots folder.

CM

On 6 May 2015, at 11:48, Rachel Krauss <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello-

Just updated the plot spatial data csvs for 12 sites.

The locations, plot IDs, plot types, and subtypes have not been altered from the previous versions. The main update was to reflect the updates in applicable modules for plant sampling in distributed plots to match the information that CI and FOPs receive.

The sites that have been updated are:
BART
DELA
DSNY
GRSM
JERC
OAES
ORNL
OSBS
SCBI
SERC
SRER
TALL

Let us know if you have any questions!

RK

**Comment by rkrauss** [comment]
Huh-

I did in my mind at least!

Just pushed and checked and they should now be updated.

Sorry about that!

RK

**Comment by schafnoir** [comment]
Thanks! I do things in my mind all the time...

On 6 May 2015, at 16:36, Rachel Krauss <notifications@github.com<mailto:notifications@github.com>> wrote:

Huh-

I did in my mind at least!

Just pushed and checked and they should now be updated.

Sorry about that!

RK
